spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yulmudiary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: email, profile

          kakao:
            client-id: ${KAKAO_CLIENT_ID:}
            # client-secret: ${KAKAO_CLIENT_SECRET:}
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  cors:
    allowed-origins:
      - http://localhost:3000
  jwt:
    secret-key: yulmudiary-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256
